name: Build Package

on:
  workflow_dispatch

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64_cortex-a53-23.05.4
          - arm_cortex-a15_neon-vfpv4-23.05.4

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        uses: sunnyqeen/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: dnsmasq-regex-openwrt mac80211-update
          V: s

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-packages
          path: ${{ github.workspace }}/bin/**/*.ipk
