name: Build Package

on:
  workflow_dispatch

jobs:
  build:
    name: ${{ matrix.version }}-${{ matrix.target }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - mediatek/filogic
          - ipq806x/generic
          - ipq40xx/generic
        version:
          - releases/23.05.4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        uses: sunnyqeen/gh-action-sdk@main
        env:
          TARGET: ${{ matrix.target }}
          VERSION_PATH: ${{ matrix.version }}
          PACKAGES: dnsmasq-regex-openwrt mac80211-update
          V: s
      - name: Write artifact name
        run: |
          ARTIFACT_NAME=${{ matrix.version }}-${{ matrix.target }}-packages
          echo ARTIFACT_NAME=${ARTIFACT_NAME//'/'/-} >> $GITHUB_ENV
      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/bin/**/*

      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive
          repository: 'sunnyqeen/openwrt-feeds'
          path: 'openwrt-feeds'
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: copy files to feeds repo
        run: |
          bash ${{ github.workspace }}/.github/scripts/ipkg-make-index-all.sh ${{ github.workspace }}/bin/targets
          mkdir -p ${{ github.workspace }}/openwrt-feeds/${{ matrix.version }}/targets
          cp -r ${{ github.workspace }}/bin/targets/* ${{ github.workspace }}/openwrt-feeds/${{ matrix.version }}/targets

      - name: Push to feeds repo
        run : |
          cd ${{ github.workspace }}/openwrt-feeds
          git add .
          changed=0
          if ! git diff --cached --exit-code; then
            changed=1
          fi
          echo "::notice::git status $changed"
          if [ $changed -ne 0 ]; then
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            git commit -m "Update packages for ${{ matrix.target }}"
            while ! git push -u origin main; do
              sleep 3
              git pull origin main
            done
          fi
