name: Build Package

on:
  workflow_dispatch

jobs:
  build:
    name: ${{ matrix.version }}-${{ matrix.target }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - mediatek/filogic
          - ipq806x/generic
        version:
          - releases/23.05.4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        uses: sunnyqeen/gh-action-sdk@main
        env:
          TARGET: ${{ matrix.target }}
          VERSION_PATH: ${{ matrix.version }}
          PACKAGES: dnsmasq-regex-openwrt mac80211-update
          V: s
      - name: Write artifact name
        run: |
          ARTIFACT_NAME=${{ matrix.version }}-${{ matrix.target }}-packages
          echo ARTIFACT_NAME=${ARTIFACT_NAME//'/'/-} >> $GITHUB_ENV
      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/bin/**/*.ipk
